

@rootUrl = http://localhost:8000

###
GET {{rootUrl}}

### auth api 

### post new user 
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fName":"suman",
    "lName":"roka",
    "email":"roka19@gmail.com",
    "phone":"09987655",
    "password":"12345@"

}

### post to active user 
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "sessionId":"69520285c00a270e0098fb5b",
    "t":"e76b4890-174c-4d34-af9b-9993804b82e3"

    
}

### lginUserEP
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email" :"roka198@gmail.com",
    "password" : "12345@"
}

### get the userProfile
GET {{rootUrl}}/api/v1/user/profile
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJva2ExOThAZ21haWwuY29tIiwiaWF0IjoxNzY3MDYzMjYzLCJleHAiOjE3NjcwNjQxNjN9.ixT2aOzB9oSGGGjWLY1KCxlBi059F09PAW_L3moKhDs

### generate the OPT 
POST {{rootUrl}}/api/v1/auth/otp
Content-Type: application/json

{
"email" : "roka198@gmail.com"
} 


###reset 
POST {{rootUrl}}/api/v1/auth/reset-password
Content-Type: application/json

{
"email" : "roka198@gmail.com",
"otp":"1792",
"password" : "123456@"



} 