

@rootUrl = http://localhost:8000

###
GET {{rootUrl}}

### auth api 

### post new user 
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fName":"suman",
    "lName":"roka",
    "email":"roka57@gmail.com",
    "phone":"09987655",
    "password":"12345@"

}

### post to active user 
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "sessionId":"694b5ef855b8cdc77932a8a4",
    "t":"d47cdf1f-8912-4dd1-8a5e-2044668e6e88"

    
}

### lginUserEP
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email" :"roka57@gmail.com",
    "password" : "12345@"
}

### get the userProfile
GET {{rootUrl}}/api/v1/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJva2E1N0BnbWFpbC5jb20iLCJpYXQiOjE3NjY5NzQ3MDUsImV4cCI6MTc2Njk3NTYwNX0._jB6n8tnAdykI2cWjWEc9VAvz74ecN7mpxxWwfdEGO8